version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: task_management
      MYSQL_USER: task_user
      MYSQL_PASSWORD: task_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  db-init:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: db-init
    restart: no
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=task_user
      - DB_PASSWORD=task_pass
      - DB_NAME=task_management
    volumes:
      - backend_migrations:/app/migrations
    entrypoint:
      - bash
      - -c
      - "if [ ! -d /app/migrations/versions ]; then sleep 60 && flask db init && flask db migrate && flask db upgrade; fi"
    depends_on:
      db:
        condition: service_started

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: task-backend
    restart: always
    environment:
      - FLASK_ENV=development
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=task_user
      - DB_PASSWORD=task_pass
      - DB_NAME=task_management
      - SECRET_KEY=supersecretkey123
    ports:
      - "5001:5001"
    volumes:
      - backend_migrations:/app/migrations
    depends_on:
      db:
        condition: service_started
      db-init:
        condition: service_completed_successfully

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    container_name: task-frontend
    restart: always
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  mysql_data:
  backend_migrations: