name: Python task management system

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: task_management
          MYSQL_USER: task_user
          MYSQL_PASSWORD: task_pass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h 127.0.0.1 -u task_user --password=task_pass"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.12"

      - name: Install dependencies and run tests
        env:
          DB_USER: task_user
          DB_PASSWORD: task_pass
          DB_HOST: 127.0.0.1
          DB_PORT: 3306
          DB_NAME: task_management
          TEST_DB_NAME: task_management
          SECRET_KEY: supersecretkey123

        run: |
          mkdir temp_files
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pytest
